# Generated by Django 5.2.9 on 2025-12-23 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_image_front', models.ImageField(upload_to='national_id_images/front/')),
                ('national_id_image_back', models.ImageField(upload_to='national_id_images/back/')),
                ('driver_license_image', models.ImageField(upload_to='driver_license_images/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_verification', to=settings.AUTH_USER_MODEL)),
                ('verification_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
