# Generated by Django 5.2.9 on 2026-01-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_subscription',
        ),
    ]
