# Generated by Django 5.2.9 on 2026-01-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_usersubscription'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_user_id_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_gateway_trans_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_gateway_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersubscription',
            name='payments_us_user_id_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersubscription',
            name='payments_us_gateway_s_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersubscription',
            name='payments_us_current__idx',
        ),
    ]
