# Generated by Django 5.2.9 on 2025-12-22 10:32

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2025)])),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('BENZINE', 'Benzine'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('seats', models.IntegerField(choices=[(4, '4 Seats'), (5, '5 Seats'), (6, '6 Seats'), (7, '7 Seats')])),
                ('doors', models.IntegerField(choices=[(2, '2 Doors'), (3, '3 Doors'), (4, '4 Doors')])),
                ('color', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('BASE', 'Base Line'), ('MID', 'Mid Line'), ('HIGH', 'High Line'), ('TOP', 'Top Line'), ('PREMIUM', 'Premium')], max_length=20)),
                ('mileage_range', models.CharField(choices=[('0-15K', '0-15,000 KM'), ('15-30K', '15,000-30,000 KM'), ('30-60K', '30,000-60,000 KM'), ('60-90K', '60,000-90,000 KM'), ('90-120K', '90,000-120,000 KM'), ('120-150K', '120,000-150,000 KM'), ('150K+', '> 150,000 KM')], max_length=20)),
                ('is_insured', models.BooleanField(default=False)),
                ('extras', models.JSONField(default=dict)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weekly_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('monthly_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('seasonal_pricing_config', models.JSONField(blank=True, default=dict)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('governorate', models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Dakahlia', 'Dakahlia'), ('Red Sea', 'Red Sea'), ('Beheira', 'Beheira'), ('Fayoum', 'Fayoum'), ('Gharbia', 'Gharbia'), ('Ismailia', 'Ismailia'), ('Monufia', 'Monufia'), ('Minya', 'Minya'), ('Qalyubia', 'Qalyubia'), ('New Valley', 'New Valley'), ('Suez', 'Suez'), ('Aswan', 'Aswan'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Sharkia', 'Sharkia'), ('South Sinai', 'South Sinai'), ('Kafr Al-Sheikh', 'Kafr Al-Sheikh'), ('Matrouh', 'Matrouh'), ('Luxor', 'Luxor'), ('Qena', 'Qena'), ('North Sinai', 'North Sinai'), ('Sohag', 'Sohag')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('BANNED', 'Banned')], db_index=True, default='ACTIVE', max_length=10)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15)),
                ('renter_confirmed', models.BooleanField(default=False)),
                ('owner_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='listings.listing')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('image_type', models.CharField(choices=[('MAIN', 'Main'), ('FRONT', 'Front'), ('BACK', 'Back'), ('LEFT', 'Left'), ('RIGHT', 'Right'), ('INTERIOR', 'Interior')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('listing', 'image_type'), name='unique_listing_image_type')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.rentalrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction', 'reviewer'), name='unique_review_per_transaction')],
            },
        ),
    ]
