# Generated by Django 5.2.9 on 2025-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='extras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seasonal_pricing_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
