# Generated by Django 5.2.9 on 2026-01-07 19:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_extras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='color',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_insured',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='mileage_range',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='model',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2025)])),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('BENZINE', 'Benzine'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('seats', models.IntegerField(choices=[(4, '4 Seats'), (5, '5 Seats'), (6, '6 Seats'), (7, '7 Seats')])),
                ('doors', models.IntegerField(choices=[(2, '2 Doors'), (3, '3 Doors'), (4, '4 Doors')])),
                ('color', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('BASE', 'Base Line'), ('MID', 'Mid Line'), ('HIGH', 'High Line'), ('TOP', 'Top Line'), ('PREMIUM', 'Premium')], max_length=20)),
                ('mileage_range', models.CharField(choices=[('0-15K', '0-15,000 KM'), ('15-30K', '15,000-30,000 KM'), ('30-60K', '30,000-60,000 KM'), ('60-90K', '60,000-90,000 KM'), ('90-120K', '90,000-120,000 KM'), ('120-150K', '120,000-150,000 KM'), ('150K+', '> 150,000 KM')], max_length=20)),
                ('is_insured', models.BooleanField(default=False)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/%Y/%m/')),
                ('image_type', models.CharField(choices=[('MAIN', 'Main'), ('FRONT', 'Front'), ('BACK', 'Back'), ('LEFT', 'Left'), ('RIGHT', 'Right'), ('INTERIOR', 'Interior')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.vehicle')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'image_type'), name='unique_vehicle_image_type')],
            },
        ),
    ]
