# Generated by Django 5.2.9 on 2026-01-11 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_brand_remove_listing_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='listing',
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='listingimage',
            name='unique_listing_image_type',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_transaction',
        ),
        migrations.RemoveConstraint(
            model_name='vehicleimage',
            name='unique_vehicle_image_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='featured_until',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='monthly_discount',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seasonal_pricing_config',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='weekly_discount',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='owner_confirmed',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='renter_confirmed',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_insured',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage_range',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='vehicleimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='listing',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='governorate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.transaction'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
