# Generated by Django 5.2.9 on 2026-01-13 08:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_transaction_remove_availability_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.AlterField(
            model_name='review',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.rentalrequest'),
        ),
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='Giza', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='monthly_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='seasonal_pricing_config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='weekly_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_type',
            field=models.CharField(choices=[('MAIN', 'Main'), ('FRONT', 'Front'), ('BACK', 'Back'), ('LEFT', 'Left'), ('RIGHT', 'Right'), ('INTERIOR', 'Interior')], default='MAIN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='owner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='renter_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='Black', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='doors',
            field=models.IntegerField(choices=[(2, '2 Doors'), (3, '3 Doors'), (4, '4 Doors')], default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='extras',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_range',
            field=models.CharField(choices=[('0-15K', '0-15,000 KM'), ('15-30K', '15,000-30,000 KM'), ('30-60K', '30,000-60,000 KM'), ('60-90K', '60,000-90,000 KM'), ('90-120K', '90,000-120,000 KM'), ('120-150K', '120,000-150,000 KM'), ('150K+', '> 150,000 KM')], default='15-30K', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image_type',
            field=models.CharField(choices=[('MAIN', 'Main'), ('FRONT', 'Front'), ('BACK', 'Back'), ('LEFT', 'Left'), ('RIGHT', 'Right'), ('INTERIOR', 'Interior')], default='MAIN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='governorate',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Dakahlia', 'Dakahlia'), ('Red Sea', 'Red Sea'), ('Beheira', 'Beheira'), ('Fayoum', 'Fayoum'), ('Gharbia', 'Gharbia'), ('Ismailia', 'Ismailia'), ('Monufia', 'Monufia'), ('Minya', 'Minya'), ('Qalyubia', 'Qalyubia'), ('New Valley', 'New Valley'), ('Suez', 'Suez'), ('Aswan', 'Aswan'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Sharkia', 'Sharkia'), ('South Sinai', 'South Sinai'), ('Kafr Al-Sheikh', 'Kafr Al-Sheikh'), ('Matrouh', 'Matrouh'), ('Luxor', 'Luxor'), ('Qena', 'Qena'), ('North Sinai', 'North Sinai'), ('Sohag', 'Sohag')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('BANNED', 'Banned')], db_index=True, default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.vehicle'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('BASE', 'Base Line'), ('MID', 'Mid Line'), ('HIGH', 'High Line'), ('TOP', 'Top Line'), ('PREMIUM', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('BENZINE', 'Benzine'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(choices=[(4, '4 Seats'), (5, '5 Seats'), (6, '6 Seats'), (7, '7 Seats')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='listingimage',
            constraint=models.UniqueConstraint(fields=('listing', 'image_type'), name='unique_listing_image_type'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('transaction', 'reviewer'), name='unique_review_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='vehicleimage',
            constraint=models.UniqueConstraint(fields=('vehicle', 'image_type'), name='unique_vehicle_image_type'),
        ),
        migrations.AddField(
            model_name='availability',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='listings.listing'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
