# Generated by Django 5.2.9 on 2026-01-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_availability_remove_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleImage',
        ),
    ]
