// Mock data for demonstrating the application
// In production, this will be replaced with API calls to Django backend
export const GOVERNORATES = [
    'Cairo',
    'Alexandria',
    'Giza',
    'Dakahlia',
    'Red Sea',
    'Luxor',
    'Aswan',
    'Port Said',
    'Suez',
    'Sharm El-Sheikh',
    'Hurghada',
    'Qalyubia',
    'Sharqia',
    'Gharbia',
    'Monufia',
];
export const TRANSMISSION_TYPES = [
    { value: 'AUTOMATIC', label: 'Automatic' },
    { value: 'MANUAL', label: 'Manual' }
];
export const FUEL_TYPES = [
    { value: 'BENZINE', label: 'Benzine' },
    { value: 'ELECTRIC', label: 'Electric' },
    { value: 'HYBRID', label: 'Hybrid' }
];
export const SEAT_COUNTS = ['4', '5', '6', '7'];
export const CATEGORIES = [
    { value: 'BASE', label: 'Base Line' },
    { value: 'MID', label: 'Mid Line' },
    { value: 'HIGH', label: 'High Line' },
    { value: 'TOP', label: 'Top Line' },
    { value: 'PREMIUM', label: 'Premium' }
];
export const FEATURES = ['GPS', 'AUX', 'Bluetooth', 'Child Seats', 'Roof Rack', 'Sunroof', 'Backup Camera', 'Air Conditioning', 'Large Trunk'];
// Mock user data
export const mockUser = {
    id: '1',
    email: 'john.doe@example.com',
    first_name: 'John',
    last_name: 'Doe',
    phone_number: '+201234567890',
    phone_verified: true,
    is_verified_identity: true,
    role: 'HOST', // RENTER or HOST
    waseet_score: 85,
    response_rate: 92,
    completion_rate: 88,
    current_subscription: {
        tier: 'PREMIUM',
        max_listings: 5,
        expires_at: '2025-02-28',
    },
    avatar: null,
};
// Mock listings data
export const mockListings = [
    {
        id: '1',
        title: 'Toyota Corolla 2023',
        brand: 'Toyota',
        model: 'Corolla',
        year: 2023,
        transmission: 'Automatic',
        fuel_type: 'Petrol',
        seats: 5,
        doors: 4,
        color: 'Silver',
        category: 'Mid-Range',
        price_per_day: 350,
        price_per_week: 2100,
        price_per_month: 7500,
        governorate: 'Cairo',
        city: 'Nasr City',
        features: ['GPS', 'Bluetooth', 'Backup Camera'],
        mileage: '10,000 - 20,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800',
        owner: {
            id: '2',
            name: 'Ahmed Ali',
            waseet_score: 92,
            response_rate: 95,
            avatar: null,
        },
        waseet_score: 92,
        avg_rating: 4.8,
        review_count: 24,
    },
    {
        id: '2',
        title: 'BMW 5 Series 2022',
        brand: 'BMW',
        model: '5 Series',
        year: 2022,
        transmission: 'Automatic',
        fuel_type: 'Petrol',
        seats: 5,
        doors: 4,
        color: 'Black',
        category: 'Luxury',
        price_per_day: 800,
        price_per_week: 5200,
        price_per_month: 18000,
        governorate: 'Alexandria',
        city: 'Miami',
        features: ['GPS', 'Bluetooth', 'Sunroof', 'Backup Camera'],
        mileage: '5,000 - 10,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1617654112368-307921291f42?w=800',
        owner: {
            id: '3',
            name: 'Mohamed Hassan',
            waseet_score: 88,
            response_rate: 90,
            avatar: null,
        },
        waseet_score: 88,
        avg_rating: 4.9,
        review_count: 31,
    },
    {
        id: '3',
        title: 'Hyundai Accent 2024',
        brand: 'Hyundai',
        model: 'Accent',
        year: 2024,
        transmission: 'Automatic',
        fuel_type: 'Petrol',
        seats: 5,
        doors: 4,
        color: 'White',
        category: 'Economy',
        price_per_day: 250,
        price_per_week: 1500,
        price_per_month: 5500,
        governorate: 'Giza',
        city: '6th of October',
        features: ['Bluetooth', 'AUX'],
        mileage: '0 - 5,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=800',
        owner: {
            id: '4',
            name: 'Sara Ibrahim',
            waseet_score: 78,
            response_rate: 85,
            avatar: null,
        },
        waseet_score: 78,
        avg_rating: 4.5,
        review_count: 12,
    },
    {
        id: '4',
        title: 'Mercedes GLC 2023',
        brand: 'Mercedes-Benz',
        model: 'GLC',
        year: 2023,
        transmission: 'Automatic',
        fuel_type: 'Petrol',
        seats: 5,
        doors: 4,
        color: 'Gray',
        category: 'Luxury',
        price_per_day: 950,
        price_per_week: 6000,
        price_per_month: 22000,
        governorate: 'Red Sea',
        city: 'Hurghada',
        features: ['GPS', 'Bluetooth', 'Sunroof', 'Backup Camera', 'Child Seats'],
        mileage: '5,000 - 10,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
        owner: {
            id: '5',
            name: 'Elite Cars Agency',
            waseet_score: 96,
            response_rate: 98,
            avatar: null,
        },
        waseet_score: 96,
        avg_rating: 4.95,
        review_count: 87,
        el_basha_badge: true,
    },
    {
        id: '5',
        title: 'Range Rover Sport 2023',
        brand: 'Land Rover',
        model: 'Range Rover Sport',
        year: 2023,
        transmission: 'Automatic',
        fuel_type: 'Petrol',
        seats: 7,
        doors: 4,
        color: 'Black',
        category: 'SUV',
        price_per_day: 1200,
        price_per_week: 7800,
        price_per_month: 28000,
        governorate: 'North Coast',
        city: 'Marina',
        features: ['GPS', 'Bluetooth', 'Sunroof', 'Backup Camera', 'Air Conditioning', 'Large Trunk'],
        mileage: '5,000 - 10,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
        owner: {
            id: '8',
            name: 'Premium Rentals',
            waseet_score: 98,
            response_rate: 99,
            avatar: null,
        },
        waseet_score: 98,
        avg_rating: 5.0,
        review_count: 142,
        el_basha_badge: true,
    },
    {
        id: '6',
        title: 'Nissan Sunny 2024',
        brand: 'Nissan',
        model: 'Sunny',
        year: 2024,
        transmission: 'Automatic',
        fuel_type: 'Petrol',
        seats: 5,
        doors: 4,
        color: 'Silver',
        category: 'Compact',
        price_per_day: 200,
        price_per_week: 1200,
        price_per_month: 4500,
        governorate: 'Cairo',
        city: 'Heliopolis',
        features: ['Bluetooth', 'Air Conditioning', 'AUX'],
        mileage: '0 - 5,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1626668893632-e7875219d375?w=800',
        owner: {
            id: '9',
            name: 'City Cars Cairo',
            waseet_score: 91,
            response_rate: 94,
            avatar: null,
        },
        waseet_score: 91,
        avg_rating: 4.7,
        review_count: 56,
        el_basha_badge: true,
    },
    {
        id: '7',
        title: 'Toyota Fortuner 2023',
        brand: 'Toyota',
        model: 'Fortuner',
        year: 2023,
        transmission: 'Automatic',
        fuel_type: 'Diesel',
        seats: 7,
        doors: 4,
        color: 'White',
        category: 'SUV',
        price_per_day: 850,
        price_per_week: 5500,
        price_per_month: 20000,
        governorate: 'Red Sea',
        city: 'Sharm El-Sheikh',
        features: ['GPS', 'Bluetooth', 'Backup Camera', 'Air Conditioning', 'Large Trunk', 'Child Seats'],
        mileage: '10,000 - 20,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
        owner: {
            id: '10',
            name: 'Coastal Adventures',
            waseet_score: 93,
            response_rate: 96,
            avatar: null,
        },
        waseet_score: 93,
        avg_rating: 4.85,
        review_count: 78,
        el_basha_badge: true,
    },
    {
        id: '8',
        title: 'Kia Picanto 2024',
        brand: 'Kia',
        model: 'Picanto',
        year: 2024,
        transmission: 'Manual',
        fuel_type: 'Petrol',
        seats: 4,
        doors: 4,
        color: 'Red',
        category: 'Compact',
        price_per_day: 180,
        price_per_week: 1000,
        price_per_month: 3800,
        governorate: 'Cairo',
        city: 'Maadi',
        features: ['Bluetooth', 'Air Conditioning'],
        mileage: '0 - 5,000 km',
        insurance_status: 'Fully Insured',
        main_image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
        owner: {
            id: '11',
            name: 'Budget Wheels',
            waseet_score: 90,
            response_rate: 92,
            avatar: null,
        },
        waseet_score: 90,
        avg_rating: 4.6,
        review_count: 45,
        el_basha_badge: true,
    },
];
// Mock rental requests
export const mockRentalRequests = [
    {
        id: '1',
        listing: mockListings[0],
        renter: {
            id: '6',
            name: 'Karim Mostafa',
            waseet_score: 82,
            phone_verified: true,
            is_verified_identity: true,
        },
        start_date: '2025-01-15',
        end_date: '2025-01-20',
        total_price: 1750,
        status: 'PENDING',
        created_at: '2025-01-05T10:30:00Z',
    },
    {
        id: '2',
        listing: mockListings[1],
        renter: {
            id: '7',
            name: 'Nour Abdel-Rahman',
            waseet_score: 90,
            phone_verified: true,
            is_verified_identity: true,
        },
        start_date: '2025-01-10',
        end_date: '2025-01-17',
        total_price: 5600,
        status: 'ACCEPTED',
        created_at: '2025-01-03T14:20:00Z',
    },
];
// Mock reviews
export const mockReviews = [
    {
        id: '1',
        listing_id: '1',
        reviewer: {
            name: 'Ali Sayed',
            avatar: null,
        },
        rating: 5,
        comment: 'Great car, clean and well-maintained. Ahmed was very responsive!',
        created_at: '2024-12-20T16:45:00Z',
    },
    {
        id: '2',
        listing_id: '1',
        reviewer: {
            name: 'Mona Khalil',
            avatar: null,
        },
        rating: 4,
        comment: 'Good experience overall. Car was as described.',
        created_at: '2024-12-15T09:30:00Z',
    },
];
// Subscription tiers
export const subscriptionTiers = [
    {
        id: 'free',
        name: 'Free Trial',
        price: 0,
        max_listings: 1,
        features: [
            '1 Car Listing',
            'Basic Support',
            'Standard Visibility',
        ],
        trial_period: '30 days from first listing',
    },
    {
        id: 'premium',
        name: 'Premium',
        price: 199,
        max_listings: 5,
        features: [
            'Up to 5 Car Listings',
            'Priority Support',
            'Featured Listings',
            'Advanced Analytics',
        ],
    },
    {
        id: 'agency_silver',
        name: 'Agency Silver',
        price: 499,
        max_listings: 15,
        features: [
            'Up to 15 Car Listings',
            '24/7 Premium Support',
            'Top Featured Listings',
            'Advanced Analytics',
            'Bulk Upload Tools',
        ],
    },
    {
        id: 'agency_gold',
        name: 'Agency Gold',
        price: 999,
        max_listings: -1, // Unlimited
        features: [
            'Unlimited Car Listings',
            '24/7 Dedicated Support',
            'Maximum Visibility',
            'Advanced Analytics',
            'Bulk Upload Tools',
            'API Access',
            'Custom Branding',
        ],
    },
];
// Mock chat messages
export const mockChatMessages = [
    {
        id: '1',
        rental_id: '2',
        sender_id: '7',
        sender_name: 'Nour Abdel-Rahman',
        message: 'Hi, is the car available for the dates I requested?',
        timestamp: '2025-01-03T14:25:00Z',
    },
    {
        id: '2',
        rental_id: '2',
        sender_id: '3',
        sender_name: 'Mohamed Hassan',
        message: 'Yes, it is! I\'ve accepted your request.',
        timestamp: '2025-01-03T14:30:00Z',
    },
    {
        id: '3',
        rental_id: '2',
        sender_id: '7',
        sender_name: 'Nour Abdel-Rahman',
        message: 'Great! Can I pick it up at 9 AM?',
        timestamp: '2025-01-03T14:35:00Z',
    },
];
export const getWaseetScoreColor = (score) => {
    if (score >= 91)
        return 'text-amber-500'; // Gold
    if (score >= 76)
        return 'text-green-500'; // Green
    if (score >= 51)
        return 'text-yellow-500'; // Yellow
    return 'text-red-500'; // Red
};
export const getWaseetScoreBadgeStyle = (score) => {
    if (score >= 91)
        return 'bg-gradient-to-r from-amber-400 to-yellow-500 text-white';
    if (score >= 76)
        return 'bg-green-500 text-white';
    if (score >= 51)
        return 'bg-yellow-500 text-gray-900';
    return 'bg-red-500 text-white';
};
